sudo: required
language: java
jdk: openjdk8
services: 
  - docker
script: 
  - mvn clean install -DskipTests -f ./commons/pom.xml
  - mvn clean install -DskipTests -f ./config-service/pom.xml
  - mvn clean install -DskipTests -f ./discovery-service/pom.xml
  - mvn clean install -DskipTests -f ./user-service/pom.xml
  - mvn clean install -DskipTests -f ./portfolio-service/pom.xml
  - mvn clean install -DskipTests -f ./trade-service/pom.xml

after_success: 
  - docker build -t sachinmudigere/stocksapp-config-service ./config-service
  - docker build -t sachinmudigere/stocksapp-discovery-service ./discovery-service
  - docker build -t sachinmudigere/stocksapp-user-service ./user-service
  - docker build -t sachinmudigere/stocksapp-portfolio-service ./portfolio-service
  - docker build -t sachinmudigere/stocksapp-trade-service ./trade-service
  #push images to docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker push sachinmudigere/stocksapp-config-service
  - docker push sachinmudigere/stocksapp-discovery-service
  - docker push sachinmudigere/stocksapp-user-service
  - docker push sachinmudigere/stocksapp-portfolio-service
  - docker push sachinmudigere/stocksapp-trade-service


