sudo: required
language: java
jdk: openjdk8
services: 
  - docker
script: 
  - mvn clean install -DskipTests -f ./config-service/pom.xml
  - docker build -t stockservice/config-service ./config-service
