sudo: required
language: java
jdk: openjdk8
services: 
  - docker

before_install:
  - docker build -t stockservice/config-service ./config-service

script: 
  - mvn clean install -DskipTests -f ./config-service/pom.xml
