version: '3'
services:
  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  config-service:
    build: ./config-service
    ports:
      - "8888:8888"
    depends_on:
      - mysql
  discovery-service:
    build: ./discovery-service
    ports:
      - "8761:8761"
    depends_on:
      - mysql
      - config-service
  user-service: 
    build: ./user-service
    ports: 
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/userservicedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysql
      - config-service
      - discovery-service


