version: '3'
services:
  mysql:
    build: ./mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
  activemq:
    build: ./activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
    environment:
      - ARTEMIS_USERNAME=admin
      - ARTEMIS_PASSWORD=password



